import { describe } from "node:test";

export const navbar = [
  { title: "صفحه اصلی", href: "/" },
  {
    title: "دسته بندی",
    children: [
      { title: "java script", href: "/category/javascript" },
      { title: "type script", href: "/category/typescript" },
    ],
  },
];

export const posts = [
  {
    id: 1,
    title: "فرق بین forEach  و map ",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 2,
    title: "2",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 3,
    title: "3",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 4,
    title: "4",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 5,
    title: "5",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 6,
    title: "6",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 7,
    title: "7",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 8,
    title: "8",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 9,
    title: "9",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 10,
    title: "10",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 11,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 12,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 13,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 14,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 15,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 16,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 17,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 18,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 19,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 20,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 21,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 22,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 23,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 24,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 25,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 26,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 27,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
  {
    id: 28,
    title: "11",
    subject: "java script",
    slug: "different-between-map-and-foreach",
    description: "different-between-map-and-foreach",
    image: "/1.jpg",
  },
];


